# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSjYKZhQi5L7br2JXsi2be6crsiOC2Ib
"""

import pandas as pd
lst={'First Name':['Pavan','sharad','pajju','shreyas'],
     'Last Name':['Ganjihal','Wadakar','Naganur','Bagoji'],
     'Type':['Full-time Employee','intern','Part-time Employee','intern'],
     'Department':['Administration','Technical','Management','Computer-science'],
     'YOE':['2','3','4','8'],
     'Salary':['10000','20000','30000','40000']}
df=pd.DataFrame(lst)
print(df)

Dep=df.groupby('Department')['Salary'].sum()
print(Dep)

